### PR TITLE
Swik 1445 email verification on signup

### PR DESCRIPTION
**Pull request by TBoonX**
Sending email code is now part of util.js
Emails are now send after signup, social signup and resetPassword.
I added the attribute authorised to the user model
Everywhere an user should e updated and an email have to be send I first try to send the email before updating the user.
I Updated the tests
Added new route for activate a user after signup - a secret is needed to use this route - secret is distinct for each user

### CODE REVIEW

**Comment by TBoonX** [comment]
The text of the emails will be changed by abi I think.

**Comment by TBoonX** [comment]
It have to be tested on one deployment to be sure it works 100%

**Comment by abijames** [comment]
Text for the emails I could find in the PR:
Line44:
'Dear '+user.forename+' '+user.surname+',\nHappy welcome to SlideWiki! You have registered your account with the username '+user.username+'. In order to activate your account please use the following link: <a href="https://'+req.info.host+'/user/activate/'+user.email+'/'+user.activate_secret+'">Activate Account</a>\nGreetings,\nThe SlideWiki team')
 +           

Line 627:
+      let connectionPromise = util.sendEMail(email, 'Dear SlideWiki user, A request has been made to reset your password. Your new password is: ' + newPassword + ' .  Please login with this password and then go to My Settings>Accounts to change it. Passwords should have 8 characters or more and can contain letters, numbers or the following characters: _ , - ~ . Thanks, The SlideWiki team');
  

Line 281:
'Dear '+user.forename+' '+user.surname+',\nHappy Welcome to SlideWiki! You have registered your account with the username '+user.username+'. In order to start using your account and learn about Getting Started with the platform please follow the link to the <a href="'+PLATFORM_INFORMATION_URL+'">SlideWiki welcome page</a>.\nGreetings,\nThe SlideWiki team'

**Comment by abijames** [comment]
I am just creating a page at /welcome to send new users to from these emails.

**Comment by TBoonX** [comment]
@abijames Right these three texts are send. I changed them but passwords could contains every character atm. The character restriction you named only applies to usernames. We just check the length of the password.

**Comment by TBoonX** [comment]
@abijames What is the status of the /welcome route? If  it will be on the release I should change the link to it (on stable and testing the route is missing)

**Pull request merged**
