### PR TITLE
SWIK-904 Integration Tests

### PR DESCRIPTION
**Pull request by rmeissn**
I've added several integration tests and am **still adding more**, in order to have a resilient API and good test coverage.

Some of these fail to execute as I expect different things than the routes are providing --> change the routes or change my expectations?

We also need to think about introducing proper logging via request.log, server.log and response.log instead of console.log

### CODE REVIEW

**Comment by rmeissn** [comment]
@TBoonX Ready to be inspected --> some tests still fail due to different expectations. Feel free to discuss about these.
I haven't covered usergroups and reset password yet, but already increased coverage by ~25% (compared to master). Created a separate Jira ticket for the missing integration tests as SWIK-905?

**Comment by TBoonX** [comment]
Existing tests are valid.
Will check if something is missing.

**Comment by TBoonX** [comment]
I corrected the handler/route.js and the tests.
Atm there is the problem that Hapi/Joi does not handle wrong Path variables. eg. GET /user/{identifier} could be called with an empty identifier. I added Joi.string().required() and Joi.string().min(1) and so on but this didnt work.
Any ideas? @rmeissn

**Comment by TBoonX** [comment]
Everything works and frontend part is already done

**Pull request merged**
